# Adapted from https://github.com/sproogen/modern-resume-theme/

# Site
# repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Adrian Călăvie
title: Resume
email: adrian.calavie06@gmail.com
phone: +40749855236
phone_title: Phone number
website: adriancalavie.github.io
# Dark Mode (true/false/never)
darkmode: false

linkedin_username: adrian-calavie
github_username: adriancalavie
about_profile_image: images/avatar.jpg
about_content: | # this will include new lines to allow paragraphs
 I am a master's student at Transilvania Univeristy of Brașov. I am interested in algorithms, data structures and AI. You can see some of my past projects on my github profile.
 
 My top skills are:
 * Algorithms
 * Data Structures
 * OOP

 I am most proficient in:  
 * C++
 * Python
 * C#

 In the past months, I've been dabbling with some Rust and Web Developement in my free time.  

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Siemens Digital Industries Software
        link: sw.siemens.com
        link_text: siemens.com
        sub_title: Software Engineer (Associate)
        caption: April 2022 - Present
        description: | # this will include new lines to allow paragraphs
            Working on a MBSE desktop solution. The tech stack is C++, Qt and Python.
      - layout: left
        title: Siemens Digital Industries Software
        link: sw.siemens.com
        link_text: siemens.com
        sub_title: Intern
        caption: October 2021 - April 2022
        description: | # this will include new lines to allow paragraphs
            Working on my bachelor's degree. The areas of R&D are DSP, concurrency and real-time changes.
      - layout: left
        title: Siemens Digital Industries Software
        link: sw.siemens.com
        link_text: siemens.com
        sub_title: Apprentice
        caption: July 2021 - September 2021
        description: | # this will include new lines to allow paragraphs
            I was an apprentice during the Curious Minds Summer School. I took courses on modern C++ and worked on a C# project.
      - layout: left
        title: General Magic
        link: generalmagic.com
        sub_title: Apprentice
        caption: March 2021 - May 2021
        description: | # this will include new lines to allow paragraphs
            Took a course named 'Neural Networks in your Hands: Tensorflow on a Mobile'. I learned the basics of AI, ML and NN.
      - layout: left
        title: Endava
        link: endava.com
        sub_title: Apprentice
        caption: September 2020 - December 2020
        description: | # this will include new lines to allow paragraphs
            Took a course named 'Developing a Web App'. I learned about web apps and versioning systems.
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
          title: Transilvania University of Brasov
          caption: 2022 - 2024
          sub_title: Master's Degree, Internet Technologies
          quote: >
            Transilvania University of Brasov is a public institution of higher education in Braşov, Romania, which through the education it offers, through scientific research and by the number of students represents one of the major universities of Romania.  
          description: | # this will include new lines to allow paragraphs
            Mainly focusing on web development and modern technologies, including AWS Cloud, Java Spring, IoT, and Networking.
      - layout: left
        title: Transilvania University of Brasov
        caption: 2019 - 2022
        sub_title: Bachelor's Degree, Computer Science
        quote: >
          Transilvania University of Brasov is a public institution of higher education in Braşov, Romania, which through the education it offers, through scientific research and by the number of students represents one of the major universities of Romania.  
        description: | # this will include new lines to allow paragraphs
          Here I took courses about Algorithms, Data Structures, Web, Android, Cloud and Programming Paradigms. Some languages I've learned are C, C++, C#, Java, Kotlin and Python. 
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 🧩 Mosaic++
        link: github.com/adriancalavie/Mosaic-plus-plus
        link_text: GitHub repo
        additional_links:
          - title:  adriancalavie/Mosaic-plus-plus
            icon: fab fa-github
            url: github.com/adriancalavie/Mosaic-plus-plus
        quote: >
          This is my first 'big' project. I cooperated with other two colleagues on making this Modern C++ app.
        description: | # this will include new lines to allow paragraphs
         Mosaic++ is a tool that produces [photomosaics](https://en.wikipedia.org/wiki/Photographic_mosaic). It offers a range of options that have an effect on the final result. It can be 
         used for entertainment purposes or be converted to an applicable tool in fields like image processing or mesh generation.

      - layout: left
        title: 📈 Plotting Project
        link: github.com/Florin9925/Plotting-
        link_text: GitHub repo
        additional_links:
          - title: Plotting Project
            icon: fab fa-github
            url: github.com/Florin9925/Plotting-
        quote: >
          This project helped me learn more about data plotting and QT.
        description: | # this will include new lines to allow paragraphs
          A plotting project made with Qt and QCustomPlot. The purpose of the app is to generate graphs for various functions and to observe the steps taken by the algorithm in order to
          obtain the correct plotting.
      - layout: left
        title: 🇱🇺 Luxembourg map traversal
        link: github.com/adriancalavie/Luxembourg
        link_text: GitHub repo
        additional_links:
          - title: github.com/adriancalavie/Luxembourg
            icon: fab fa-github
            url: github.com/adriancalavie/Luxembourg
        # quote: >
        #   This project ...
        description: | # this will include new lines to allow paragraphs         
          One of the homeworks at a Graph Theory course I took required us to compute the shortest path between
          two points on the map of Luxembourg. We were given the input data as a massive xml file consisting of
          nodes and edges and our task was to translate the latitude and longitude values into pixels on the screen,
          to plot them and let the user choose two points on the map, the points to be chosen would be the closest to
          where the mouse clicks. Also, we were required to implement both Dijkstra's and Bellman-Ford's algorithm.
      - layout: left 
        title: 🤖 AI puzzle solver
        link: github.com/adriancalavie/AI-puzzle
        link_text: GitHub repo
        additional_links:
          - title: github.com/adriancalavie/AI-puzzle
            icon: fab fa-github
            url: github.com/adriancalavie/AI-puzzle
        #  quote: >
        #   This project 
        description: | # this will include new lines to allow paragraphs
          This C++ code from 2019 solves the x-puzzle problem. I wrote it in my first year at University.
          The algorithm uses states to verify if the current puzzle is in 'final' form or not. It firstly checks if the
          game is solvable or not based on the information on this [site](http://kevingong.com/Math/SixteenPuzzle.html).
          If it is solvable, it searches for the best move set(the one with the lowest number of moves that reaches a 'final' state) using A*.
 
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in computer science some of my other interests and hobbies are:
      - Climbing
      - Running
      - Gaming

# Footer

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
